spring.application.name=backend

#database connection
spring.datasource.url=jdbc:postgresql://localhost:5435/devlog
spring.datasource.username=devlog_user
spring.datasource.password=devlog_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
